# Generated by Django 4.0.10 on 2025-01-26 18:50

import core.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_vetter', models.BooleanField(default=False)),
                ('is_verifier', models.BooleanField(default=False)),
                ('is_publisher', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('mission', models.TextField()),
                ('goals', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarding_name', models.CharField(max_length=100)),
                ('onboarding_type', models.CharField(choices=[('operations', 'Operational'), ('leave', 'Leave taking'), ('training', 'Training'), ('other', 'Other')], default='test', help_text='Verification status', max_length=50)),
                ('notes', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Pending Verification'), ('vetting', 'Vetting'), ('verified', 'Verified'), ('published', 'Published')], default='draft', help_text='Verification status', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('emp_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OnboardingNote',
                'verbose_name_plural': 'OnboardingNotes',
            },
        ),
        migrations.CreateModel(
            name='OnboardingNoteImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to=core.helpers.image_path)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.onboarding')),
            ],
            options={
                'verbose_name': 'Onboarding Notes Images',
                'verbose_name_plural': 'Onboarding Notes Images',
            },
        ),
    ]
