# Generated by Django 4.0.10 on 2025-01-26 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_onboarding_emp_creator_onboarding_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='core.department'),
        ),
    ]
