# Generated by Django 4.0.10 on 2025-01-27 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_onboardingstep_onboardingstepimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingstep',
            name='onboarding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_step', to='core.onboarding'),
        ),
    ]
