# Generated by Django 4.0.10 on 2025-01-27 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_onboardingstep_onboarding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboardingstep',
            name='onboarding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboardingsteps', to='core.onboarding'),
        ),
        migrations.AlterField(
            model_name='onboardingstepimages',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.onboardingstep'),
        ),
    ]
