# Generated by Django 4.0.10 on 2025-01-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_onboardingstep_onboarding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingstep',
            name='onboarding',
        ),
        migrations.AddField(
            model_name='onboarding',
            name='onboarding_step',
            field=models.ManyToManyField(to='core.onboardingstep'),
        ),
    ]
