# Generated by Django 4.0.10 on 2025-01-27 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_onboardingstep_onboarding_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='onboarding',
            old_name='onboarding_step',
            new_name='steps',
        ),
        migrations.AddField(
            model_name='onboardingstep',
            name='main_onboarding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.onboarding'),
        ),
    ]
