# Generated by Django 4.0.10 on 2025-01-27 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_onboarding_step_onboarding_steps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboarding',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='onboardingstep',
            name='main_onboarding',
        ),
        migrations.AddField(
            model_name='onboardingstep',
            name='onboarding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboardingstep', to='core.onboarding'),
        ),
    ]
