# Generated by Django 4.0.10 on 2025-01-29 15:39

import core.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_policy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'Policies', 'verbose_name_plural': 'Policies'},
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowledge_title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('version', models.CharField(blank=True, default='v1.0', max_length=20, null=True)),
                ('knowledge_category', models.CharField(blank=True, choices=[('onboarding', 'Onboarding'), ('policy', 'Policy'), ('procedure', 'Procedure'), ('compliance', 'Compliance'), ('general', 'General')], default='general', max_length=100)),
                ('document_type', models.CharField(blank=True, choices=[('article', 'Article'), ('conference_paper', 'Conference paper'), ('research_paper', 'Research paper'), ('book', 'Book'), ('chapter', 'Chapter')], max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to=core.helpers.document_path)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Pending Verification'), ('vetting', 'Vetting'), ('verified', 'Verified'), ('published', 'Published')], default='draft', help_text='Verification status', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_knowledge', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_department', to='core.department')),
                ('linked_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_policy', to='core.policy')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_knowledge', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_knowledge', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Knowledge Base',
                'verbose_name_plural': 'Knowledge Base',
            },
        ),
    ]
